import org.jetbrains.changelog.Changelog

plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev.legacyforge'
    id "me.modmuss50.mod-publish-plugin" version "1.1.0"
}

mixin {
    add(sourceSets.main, "${mod_id}.refmap.json")

    config("${mod_id}.mixins.json")
    config("${mod_id}.forge.mixins.json")
}

legacyForge {
    version = "${minecraft_version}-${forge_version}"

    validateAccessTransformers = true

    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers = ["src/main/resources/META-INF/accesstransformer.cfg"]
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        client {
            client()
        }
        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        server {
            server()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

repositories {
    maven { url "https://maven.shedaniel.me/" }
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven/"
    }
}

dependencies {
    compileOnly project(":common")
    implementation 'org.jetbrains:annotations:25.0.0'
    annotationProcessor("org.spongepowered:mixin:0.8.5-SNAPSHOT:processor")
    modApi("me.shedaniel.cloth:cloth-config-forge:${cloth_config_version}")
    modImplementation 'maven.modrinth:small-ships:58DKgNnY'
    api("org.projectlombok:lombok:1.18.36")
    annotationProcessor("org.projectlombok:lombok:1.18.36")
}

configurations.create('fabricDatagen')
dependencies {
    fabricDatagen project(path: ':fabric', configuration: 'datagenOutput')
}

processResources {
    from configurations.fabricDatagen.singleFile
}

jar {
    finalizedBy('reobfJar')
    manifest.attributes([
            "MixinConfigs": "${mod_id}.mixins.json,${mod_id}.forge.mixins.json"
    ])
}

publishMods {
    type = STABLE
    version = "${project.version}+${minecraft_version}"
    changelog = project(":common").changelog.renderItem(project(":common").changelog
            .getLatest()
            .withHeader(false)
            .withEmptySections(false),
            Changelog.OutputType.MARKDOWN
    )
    file = reobfJar.archiveFile

    curseforge("curseforgeForge") {
        projectId = "1441109"
        accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
        minecraftVersions.add(minecraft_version)
        javaVersions.add(JavaVersion.VERSION_17)
        modLoaders.add("forge")
        clientRequired = true
        serverRequired = true
        requires("cloth-config")
        requires("small-ships")
        optional("modmenu")
    }

    modrinth("modrinthForge") {
        projectId = "HRWfY2Uh"
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")
        minecraftVersions.add(project.minecraft_version)
        modLoaders.add("forge")
        requires("cloth-config")
        requires("small-ships")
        requires("fabric-api")
        requires("cardinal-components-api")
        optional("modmenu")
    }
}
